<x-filament-widgets::widget>

    <x-filament::section>

        <x-slot name="heading">
            Events
        </x-slot>

        <x-slot name="description">
            GA4 events generated by visitors.
        </x-slot>

        @php
            $rows =
                $this->getRows();
        @endphp

        <div class="overflow-x-auto">

            <table class="w-full text-sm">

                <thead>

                    <tr
                        class="
                            border-b
                            border-gray-200
                            dark:border-white/10
                        "
                    >

                        <th
                            class="
                                px-3
                                py-3
                                text-left
                            "
                        >
                            Event
                        </th>

                        <th
                            class="
                                px-3
                                py-3
                                text-left
                            "
                        >
                            Type
                        </th>

                        <th
                            class="
                                px-3
                                py-3
                                text-right
                            "
                        >
                            Count
                        </th>

                        <th
                            class="
                                px-3
                                py-3
                                text-right
                            "
                        >
                            Users
                        </th>

                        <th
                            class="
                                px-3
                                py-3
                                text-right
                            "
                        >
                            Key Events
                        </th>

                    </tr>

                </thead>

                <tbody
                    class="
                        divide-y
                        divide-gray-100
                        dark:divide-white/5
                    "
                >

                    @forelse(
                        $rows as $row
                    )

                        @php
                            $type =
                                $this
                                    ->eventType(
                                        $row
                                            ->event_name
                                    );
                        @endphp

                        <tr>

                            <td
                                class="
                                    px-3
                                    py-3
                                    font-medium
                                    text-gray-950
                                    dark:text-white
                                "
                            >
                                {{
                                    $row
                                        ->event_name
                                }}
                            </td>

                            <td
                                class="
                                    px-3
                                    py-3
                                "
                            >

                                <x-filament::badge
                                    :color="
                                        $type[
                                            'color'
                                        ]
                                    "
                                >
                                    {{
                                        $type[
                                            'label'
                                        ]
                                    }}
                                </x-filament::badge>

                            </td>

                            <td
                                class="
                                    px-3
                                    py-3
                                    text-right
                                "
                            >
                                {{
                                    number_format(
                                        $row
                                            ->event_count
                                    )
                                }}
                            </td>

                            <td
                                class="
                                    px-3
                                    py-3
                                    text-right
                                "
                            >
                                {{
                                    number_format(
                                        $row
                                            ->total_users
                                    )
                                }}
                            </td>

                            <td
                                class="
                                    px-3
                                    py-3
                                    text-right
                                    font-semibold
                                "
                            >
                                {{
                                    number_format(
                                        $row
                                            ->key_events,
                                        0
                                    )
                                }}
                            </td>

                        </tr>

                    @empty

                        <tr>

                            <td
                                colspan="5"
                                class="
                                    px-3
                                    py-8
                                    text-center
                                    text-gray-500
                                "
                            >
                                No event data found.
                            </td>

                        </tr>

                    @endforelse

                </tbody>

            </table>

        </div>

    </x-filament::section>

</x-filament-widgets::widget>